Занятие 1.Задачи 1-5 на проверку
js-tasks-ru/jsbasic-20210225_bez-kupyr pull request #3
Opened 2021-03-03 12:48 UTC by ITihonyaJS

2021-03-03 19:12 UTC, SinimaWath requested changes

2021-03-03 19:12 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  let num = typeof(n);
Не говорящее название. Тогда это не num, а typeOfArgument.

Но в твоем случае, создавать переменную - это лишнее. Так как ты ее используешь только в if. Можно переписать так:
```
if (typeof(n) !== 'number') {
  return
}
```

2021-03-03 19:12 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  return a
Название переменных не говорящие(j, a), другой разработчик не поймет, зачем она нужна:
переменная должна говорить:
- Что она хранит
- Для чего хранит

Давай придумаем, что-то более подходящее )

2021-03-03 19:12 UTC, SinimaWath commented on 1-module/1-task/index.js
> +    console.log('Введите числовое значение');
Это нормально. Но в данной, задаче это лишнее. Лучше убрать

2021-03-03 19:12 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return true
- Эту функцию лучше упростить, до одной строчки: `return  name === null && ...`
- Вместо метода indexOf, стоит использовать, новый более подходящий, `includes`
- Тут в идеале, должно быть всего 3 условия: `return <условие 1> && <условие 2> && <условие 3>`

2021-03-03 19:12 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  return newString
Эту строчку можно упростить вместе с шаблонными строками: 

```
return `${firstLetter}${endString}`
```

2021-03-03 19:12 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  const SECOND_VALUE = 'XXX'.toLowerCase();
Правильно, вынес. Только такие переменные-настройки, обычно хранят, в глобальной области:
```
  const FIRST_VALUE = '1xBet'.toLowerCase();
  const SECOND_VALUE = 'XXX'.toLowerCase(); 

function checkSpam....

```

2021-03-03 19:12 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  return false;
Можно упростить до одной строчки: `return ...`

2021-03-03 19:12 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  if(toSmallText.indexOf(FIRST_VALUE) != -1 || toSmallText.indexOf(SECOND_VALUE) != -1){
Лучше использовать метод `includes()`, у негоо более удобный интерфейс использование

2021-03-03 19:12 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  let toSmallText = string.toLowerCase();
toSmallText, не подходящее название чутка. 

Больше подходит: `textInLowerCase`

2021-03-03 19:12 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  }
Правильно будет пустую строку.

2021-03-03 19:12 UTC, SinimaWath commented on 1-module/5-task/index.js
> +    return newString
можно упростить до одной строки, без создания переменных

2021-03-10 14:55 UTC, ITihonyaJS commented
"Корректировка задач 1-й модуль и задачи 2-й модуль"

2021-03-10 18:05 UTC, SinimaWath requested changes

2021-03-10 18:05 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  }*/
Нужно убрать

2021-03-10 18:05 UTC, SinimaWath commented on 1-module/1-task/index.js
> +    console.log('Введите числовое значение');
Up. Нужно убрать комменты

2021-03-10 18:05 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  return false;
Лишнее тут

2021-03-10 18:05 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  }*/
Лишние комментарии нужно убирать

2021-03-10 18:05 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  let newString;
ненужная переменная

2021-03-10 18:05 UTC, SinimaWath commented on 2-module/1-task/index.js
> +  let isNumber = 0;
Это лишняя логика.

Если не будет свойств с ЗП, то sumSalaries и так будет: 0

2021-03-10 18:05 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  let endString = string.slice(1);
Так как это неизменяемые значения, то это const - переменные

2021-03-10 18:05 UTC, SinimaWath commented on 2-module/1-task/index.js
> +    }
Обьедини в один if, сейчас достаточно большая вложенность из-за if. Можно упростть до:
```
if (typeof salaries[prop] === "number" && isFinite()) {
  ...
}
```

2021-03-10 18:05 UTC, SinimaWath commented on 2-module/2-task/index.js
> +  return true;
Упрости до одной строчки: `return Object.keys(....`

2021-03-10 18:05 UTC, SinimaWath commented on 2-module/3-task/index.js
>  };
Маленькая рекомендация. Лучше в обьектах, заранее инициализировать, свойства которые будут использоваться.
```
let calculator = {
  firstOperand: null,
  secondOperand: null,
  
  read(..) ...
}
```

Зачем?
Разработчик, который будет читать этот код, сможет сразу понять, что в обьекте есть такие поля: `firstOperand `, `secondOperand `.

В твоем случае, это свойства `a`, `b`

2021-03-11 07:49 UTC, SinimaWath approved these changes

2021-03-11 07:50 UTC, merged