3-й модуль. Задачи 1-2. На проверку
js-tasks-ru/jsbasic-20210225_bez-kupyr pull request #4
Opened 2021-03-14 08:45 UTC by ITihonyaJS

2021-03-14 08:45 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-03-14 18:04 UTC, SinimaWath requested changes

2021-03-14 18:04 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  });
Есть специальный метод map, про который рассказывал на лекции. Используй его тут

2021-03-14 18:04 UTC, SinimaWath commented on 3-module/2-task/index.js
> +let arr = [5,15,105,37,24,1002,75,12,44,13,98,32, 3, 8,63, 1];
Забыл убрал информацию для тестирования, ее нужно убрать

2021-03-14 18:04 UTC, SinimaWath commented on 3-module/2-task/index.js
> +  return newArray;
Используй filter, который рассказывал на лекции

2021-03-15 13:50 UTC, SinimaWath requested changes

2021-03-15 13:50 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return nameUsers;
А зачем тут промежуточная переменная?

2021-03-15 13:50 UTC, SinimaWath commented on 3-module/2-task/index.js
> +  return newArray;
Зачем тут тоже промежуточная переменная?

2021-03-15 13:50 UTC, SinimaWath commented on 3-module/3-task/index.js
> +    newArrayWords.push(word);
Как-то очень сложно (

Чтобы сделать первую букву заглавной достаточно: `word[0].toUpperCase() + word.slice(1)`

2021-03-15 13:50 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  console.log(arrayWords)
Это лишнее

2021-03-15 13:50 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  const arrayWords = str.split("-");
Можно через `.`, соеденять разные вызовы методов:
```
str.split('-').map(...).join('')
```

В данном случае промежуточные переменные лишние

2021-03-15 13:50 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  })
filter

2021-03-15 13:50 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  })
А это можно заменить на `map(...).join('\n')`

2021-03-15 13:50 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  })
filter

2021-03-15 13:50 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  objectMinAndMaxNumbers.max = Number(arrayNumbers[arrayNumbers.length-1]);
Давай вместо sort, используем Math.min и Math.max + спред оператор `Maith.min(...array)`

2021-03-15 13:50 UTC, SinimaWath commented on 3-module/5-task/index.js
> +    return null;
Если там один, то нужно вернуть не null, а вернуть 2 раза одно и тоже значение в min, max

2021-03-17 19:42 UTC, SinimaWath requested changes

2021-03-17 19:42 UTC, SinimaWath commented on 3-module/3-task/index.js
> +    return word;
Это можно упростить до тернарного оператора(условный оператор), я его не показывал на лекции:
https://learn.javascript.ru/ifelse#uslovnyy-operator

`index != 0 ? word[0].toUpperCase() + word.slice(1) : word`

2021-03-17 19:42 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  let arrayWords = str.split("-").map((word,index) => {
Не стоит создавать лишнюю временную переменную, а сразу вернуть значение:
```
return str.split('-')...
```

2021-03-17 19:42 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  }).join("\n");
Давай обойдемся краткой записию, без return:`` `() => `${...}````

2021-03-18 15:44 UTC, SinimaWath approved these changes

2021-03-18 15:44 UTC, merged