4-й модуль. Задачи 1-2.На проверку
js-tasks-ru/jsbasic-20210225_bez-kupyr pull request #5
Opened 2021-03-22 19:33 UTC by ITihonyaJS

2021-03-22 19:33 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-03-22 21:53 UTC, SinimaWath requested changes

2021-03-22 21:53 UTC, SinimaWath commented on 4-module/1-task/index.js
> +    ulList.append(liList);
Давай попробуем без промежуточно елемента. А сразу добавлять шаблон. `<li>.... </li>`

2021-03-22 21:53 UTC, SinimaWath commented on 4-module/1-task/index.js
> +  bodyTeg.append(ulList);
Зачем добавляешь в body? Попробуй не добавлять и посмотри что будет

2021-03-22 21:53 UTC, SinimaWath commented on 4-module/2-task/index.js
> +  }
У тебя индексы матрицы(таблица) выглядит вот так:

```
| 1;1 | 1;2 | 1;3 |
-------------------
| 2;1 | 2;2 | 2;3 |
-------------------
| 3;1 | 3;2 | 3;3 |
```
Как ты видишь у диагональных есть что-то общее.

И в твоем решении можно обойтись без второго цикла: 

`for (let td of tdColletions)`


Попробуй переписать на обычный for (let i = 0; ...) с индексами

2021-03-23 14:33 UTC, SinimaWath requested changes

2021-03-23 14:33 UTC, SinimaWath commented on 4-module/2-task/index.js
> +    if(tdCollections[i].cellIndex === i){
Давай попробуем без if :)

2021-03-23 14:33 UTC, SinimaWath commented on 4-module/2-task/index.js
> +    if(tdCollections[i].cellIndex === i){
У тебя есть номер строчки и номер столбца, поэтому ты можешь сразу получить диагональный элемент

2021-03-25 19:22 UTC, SinimaWath approved these changes

2021-03-25 19:22 UTC, merged